FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build

ARG CONFIG=RELEASE
ARG VERSAO=1.0.0

WORKDIR /build

CMD ls

COPY ./Financas.sln .
COPY ./src ./src
COPY ./test ./test/
RUN dotnet restore

RUN dotnet publish ./src/TaxaJuros.Api/ -c ${CONFIG} -o out /p:Version=${VERSAO}

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
EXPOSE 80

COPY --from=build /build/out/. ./

ENTRYPOINT ["dotnet", "TaxaJuros.Api.dll"]